### ISSUE TITLE
Legacy context API has been detected within a strict-mode tree.

### ISSUE THREAD

**Issue by srinivasaltair** [LouisBarranqueiro/reapop#334]
<img width="1283" alt="Screenshot 2020-12-23 at 9 58 48 PM" src="https://user-images.githubusercontent.com/8829163/103018005-7ebb8300-456a-11eb-918c-2231f51de26b.png">

This is the warning that is been showing. Please help

I'm using 
React v17.0.1
React-redux: v7.2.2

**Comment by LouisBarranqueiro** [comment]
👋 @srinivasaltair which version of Reapop do you use?

**Comment by LouisBarranqueiro** [comment]
I found https://github.com/reactjs/react-transition-group/issues/429 and I upgraded all the dependencies of the project as well as `react-transition-group` a few days ago (https://github.com/LouisBarranqueiro/reapop/commit/28d16cfb6f9304611a34a90dd156b1f91dd9da8c). I will release a new version today.

**Comment by srinivasaltair** [comment]
I'm using the latest version of the Reapop v3.0.1.

Thank you for the quick response.

**Comment by LouisBarranqueiro** [comment]
I just released v3.0.2. Let me know if the warning is gone 🙂

**Comment by srinivasaltair** [comment]
Actually no, I see the only file changed is package.json. And the issue still persists. 😔

**Comment by LouisBarranqueiro** [comment]
It's not the same issue. This is related to the way reapop uses `react-transition-group`. I will work on it but you don't have to worry it's just a deprecation warning.

**Comment by srinivasaltair** [comment]
Thank you.
